import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

export type Language = "en-AU" | "ar-EG";

type Translations = Record<Language, Record<string, string>>;

const translations: Translations = {
  "en-AU": {
    "language.australian": "Australian",
    "language.masri": "Masri",
    "header.logoAlt": "Burn Me While I'm Hot",
    "nav.upload": "Upload",
    "nav.play": "Play",
    "nav.about": "About",
    "about.title": "Why do you want to get burned?",
    "about.body": `live video synth.
live video samizdat.

encrypt data, or encrypt perception.

video is usually the opposite of private. it is one of the most exposed
mediums we have, the easiest to duplicate, the easiest to circulate, the
hardest to contain. anyone can record you, repost you, archive you,
watch you without context, without consent, without you ever knowing.
the question is not just how to keep something yours anymore. the
question is what kind of machine lets you exist in public without being
completely legible.

maybe you don't need to disappear.

but you do need to become harder to read.


not privacy through absence, but privacy through interpretation.

this is not about replacing cryptography. it is about letting
cryptography live inside a medium that already moves through culture on
its own. instead of pushing everything down into invisible layers of
math and code, the surface itself starts to carry the work. what you see
becomes part of how meaning is shaped. layered, shifting, slightly off,
suspicious in that CYOA escaping through the mirrors of victorian halls
at midnight.

and now its not just an mp4.

it becomes an mp4p.

an mp4-privy.

burn me while i'm hot does not pull meaning away from view. it lets it
sit right in front of everyone, but in a form that refuses to settle
into something readable on its own. the content moves freely. the
meaning does not. the synth is no longer just decoration. it burns
itself into the video.

so the question shifts.

not how do you regain the keys to agentic privacy.
but how do you burn yourself into the surface in a way that stays yours.

why live video?

live video is computationally much more demandingly random. real-time
synthesis introduces variation at the level of frame timing, internal
state, and render order. those differences are small, but they are
stable enough to matter cryptographically and unstable enough to resist
replay.

here, the frames of the live synth are treated as input to the
encryption process. each burn frame becomes part of the key schedule for
the visual payloads. the exact bytes of the frame are hashed and folded
into per-frame key material. that means the encryption context is bound
not only to abstract settings like prompt or seed, but to the concrete
result of a specific render that happened at a specific moment.

live video provides a time-bound, non-replayable visual source that the
encryption pipeline can depend on, making restoration inseparable from
the exact circumstances in which the burn was created.

how it works
1. upload a video where you are clearly visible in frame
2. sam3 runs on the footage and builds a frame by frame mask of you
3. pick a y2k style and prompt set to visually transform with loud
colours, patterns, and overlays
4. hit burn to create the synth output and bind the masked pixels
through per frame visual cipher keying
5. export the mp4p container together with the separate key file used
for decryption later
6. load the mp4p into the player to view the burned version of the video
7. import the key file to reverse the visual cipher and reconstruct the
masked areas

how encryption and decryption happen
encryption starts with a secret input, keyMaterial, and a fixed set of
public visual-cipher metadata: prompt, stable params, seed, and mask
configuration. from these, the system derives a base_key by hashing
keyMaterial, the prompt, the params, and the seed with sha256.

the burn video is rendered and its frames become cryptographic input.
for each frame, the exact frame bytes are hashed to produce a
frame_hash. this hash and the frame index are combined with the base key
using hmac-sha256 to derive a unique frame_key.

from each frame_key, a keystream is generated by running hmac-sha256
with incrementing counters and truncating the output to the full frame
rgb length (height × width × 3). this keystream is xor-ed with the
original video's rgb pixels inside the mask. pixels outside the mask are
zeroed. the result is encrypted visual noise tied to that specific burn
frame.

each encrypted frame is stored as a png with rgba channels, where rgb
contains the encrypted pixels and alpha contains the mask. these frames
are base64-encoded and saved in the mp4p file as encryptedMaskFrames,
with a maskFrameIndexMap linking each payload to its burn frame. in
parallel, the original and synthed videos are encrypted with aes-gcm
using a key derived from keyMaterial via pbkdf2, with salt, iv, and auth
tag stored in mp4p metadata.

decryption requires the mp4p file, the key file, and the exact burn
frames. the system re-derives the same base_key, recomputes each
frame_key, regenerates the keystream, and xor-s it with the stored
payloads to recover the masked pixels. these pixels are composited back
onto the burn frames using the stored mask and mask mode.

if the burn frames and key material match, the masked regions resolve.
if either differs, the keystream diverges and the output stays noise.

some mp4p specifics
the format is a cryptographic container that holds encrypted media
streams, visual-cipher payloads, and the metadata needed to recompute
them. the original video exists inside it as aes-gcm encrypted bytes. it
is not extractable without key material, existing only as per-frame
visual payloads that are mathematically bound to a specific burn video
and a key file.

without that exact burn context and the matching key material, there is
nothing meaningful to decode, no partial frames to recover, no
underlying stream to dump. mp4p stores encrypted video bytes plus the
conditions under which a video can be reconstructed, and outside of
those conditions the format resolves only to ciphertext and synchronized
noise.

improvements
scale + speed. scale + speeeeeedd.

1. handle longer videos
2. better sam3 masking and real time not pre-processed
3. the current 1.3b lora works, but it loses a lot of fine detail
compared to its 14b counterpart

all of this ultimately comes down to memory, ram, gpus etc

why y2k?
because as everything gets endshitified, y2k is the style that still
remembers web1, when things felt possible and not drowned in polarizing
bot slop (nothing against bots, everything against their overlords)



privacy is a right.`,
    "inputControls.title": "Input & Controls",
    "videoInput.title": "Video Input",
    "videoInput.initializing": "Initializing video...",
    "videoInput.errorLabel": "Video error:",
    "videoInput.dragBox": "Drag to box the person",
    "videoInput.burning": "Burning...",
    "videoInput.uploadToBegin": "Upload a vid to begin",
    "videoInput.changeVideo": "Change Video",
    "videoInput.play": "Play",
    "videoInput.pause": "Pause",
    "pipeline.title": "Pipeline",
    "pipeline.selectPlaceholder": "Select a pipeline",
    "style.title": "Style",
    "sam3.title": "SAM3 Mask",
    "sam3.requiresAccessPrefix": "Requires HF access to",
    "sam3.requiresAccessSuffix": ". Request access before generating masks.",
    "sam3.generating": "Generating...",
    "sam3.regenerateWithBox": "Regenerate with Box",
    "sam3.regenerateMask": "Regenerate Mask",
    "sam3.useBoxPrompt": "Use Box Prompt",
    "sam3.cancelBox": "Cancel Box",
    "sam3.noMaskDetected": "No mask detected. Try box prompt for better focus.",
    "sam3.drawBoxHint": "Draw a box on the preview, then regenerate.",
    "burn.title": "Burn",
    "burn.start": "Start Burn",
    "burn.cancel": "Cancel Burn",
    "burn.delete": "Delete Burn",
    "burn.statusFromStart": "{status} from start.",
    "burn.status.recording": "Recording",
    "burn.status.preparing": "Preparing",
    "export.exporting": "Exporting...",
    "export.exportMp4p": "Export MP4P",
    "export.downloadKeyFile": "Download Key File",
    "videoOutput.title": "Video Output",
    "videoOutput.startPipeline": "Start Pipeline",
    "videoOutput.startPipelineHint": "Click to start the pipeline.",
    "videoOutput.tapToPlay": "Tap to Play",
    "videoOutput.autoplayBlocked": "Browser paused autoplay. Click to resume.",
    "videoOutput.downloadingModels": "Downloading models...",
    "videoOutput.warmingPipeline": "Warming up pipeline...",
    "videoOutput.generatingMask": "Generating SAM3 mask...",
    "videoOutput.burning": "Burning...",
    "videoOutput.loading": "Loading...",
    "videoOutput.connecting": "Connecting...",
    "videoOutput.waitingForVideo": "Waiting for video...",
    "play.title": "Play MP4P",
    "play.loadMp4p": "Load MP4P",
    "play.loadKeyFile": "Load Key File",
    "play.loadingMp4p": "Loading MP4P...",
    "play.noVideoLoaded": "No video loaded.",
    "play.play": "Play",
    "play.pause": "Pause",
    "play.stop": "Stop",
    "play.restart": "Restart",
    "play.skipBack": "-5s",
    "play.skipForward": "+5s",
    "play.volume": "Volume",
    "play.unmute": "Unmute",
    "play.mute": "Mute",
    "play.unlock": "Unlock",
    "play.decrypting": "Decrypting...",
    "play.decryptWithKey": "Decrypt with Key",
    "play.error.loadFailed": "Failed to load MP4P",
    "play.error.invalidKeyFile": "Invalid key file",
    "play.error.decryptFailed": "Decrypt failed",
    "settings.title": "Settings",
    "settings.pipelineId": "Pipeline ID",
    "settings.selectPipeline": "Select a pipeline",
    "settings.lora.label": "Y2K LoRA",
    "settings.lora.tooltip": "Enable the default Y2K LoRA (scale 1.0). Toggle only when paused.",
    "settings.toggle.on": "On",
    "settings.toggle.off": "Off",
    "settings.lora.pauseToToggle": "Pause video to toggle the LoRA.",
    "settings.quantization.none": "None",
    "settings.quantization.fp8": "fp8_e4m3fn (Dynamic)",
    "settings.spout.on": "ON",
    "settings.spout.off": "OFF",
    "settings.spout.senderName": "Sender Name:",
    "settings.spout.senderTooltip": "The name of the sender that will send video to Spout-compatible apps like TouchDesigner, Resolume, OBS.",
    "settings.spout.placeholder": "ScopeOut",
    "param.height.label": "Height:",
    "param.height.tooltip": "Output video height in pixels. Higher values produce more detailed vertical resolution but reduces speed.",
    "param.width.label": "Width:",
    "param.width.tooltip": "Output video width in pixels. Higher values produce more detailed horizontal resolution but reduces speed.",
    "param.seed.label": "Seed:",
    "param.seed.tooltip": "Random seed for reproducible generation. Using the same seed with the same settings will produce similar results.",
    "param.denoisingSteps.label": "Denoising Step List",
    "param.denoisingSteps.tooltip": "List of denoising timesteps used in diffusion. Values must be in descending order. Lower values mean less noise to remove. More steps can improve quality but reduce speed.",
    "param.noiseController.label": "Noise Controller:",
    "param.noiseController.tooltip": "Enables automatic noise scale adjustment based on detected motion. Disable for manual control via Noise Scale.",
    "param.noiseScale.label": "Noise Scale:",
    "param.noiseScale.tooltip": "Controls the amount of noise added during generation. Higher values add more variation and creativity and lower values produce more stable results.",
    "param.quantization.label": "Quantization:",
    "param.quantization.tooltip": "Quantization method for the diffusion model. fp8_e4m3fn (Dynamic) reduces memory usage, but might affect performance and quality. None uses full precision and uses more memory, but does not affect performance and quality.",
    "param.kvCacheAttentionBias.label": "Cache Bias:",
    "param.kvCacheAttentionBias.tooltip": "Controls how much to rely on past frames in the cache during generation. A lower value can help mitigate error accumulation and prevent repetitive motion. Uses log scale: 1.0 = full reliance on past frames, smaller values = less reliance on past frames. Typical values: 0.3-0.7 for moderate effect, 0.1-0.2 for strong effect.",
    "param.loraMergeStrategy.label": "LoRA Strategy:",
    "param.loraMergeStrategy.tooltip": "LoRA merge strategy affects performance and update capabilities. Permanent Merge: Maximum performance, no runtime updates. Runtime PEFT: Lower performance, instant runtime updates.",
    "param.loraScale.label": "Scale:",
    "param.loraScale.tooltip": "Adjust LoRA strength. Updates automatically when you release the slider or use +/- buttons. Typical values: 0.0 = no effect, 1.0 = full strength. Full range -10.0 to 10.0 available depending on LoRA specifications.",
    "param.loraScaleDisabledDuringStream.label": "Scale:",
    "param.loraScaleDisabledDuringStream.tooltip": "Runtime adjustment is disabled with Permanent Merge strategy. LoRA scales are fixed at load time. Typical values: 0.0 = no effect, 1.0 = full strength. Full range -10.0 to 10.0 available depending on LoRA specifications.",
    "param.spoutSender.label": "Spout Sender:",
    "param.spoutSender.tooltip": "The configuration of the sender that will send video to Spout-compatible apps like TouchDesigner, Resolume, OBS.",
    "lora.title": "LoRA Adapters",
    "lora.refreshTitle": "Refresh LoRA list",
    "lora.addTitle": "Add LoRA",
    "lora.addDisabledTitle": "Cannot add LoRAs while streaming",
    "lora.noneConfiguredPrefix": "No LoRA adapters configured. Follow the",
    "lora.noneConfiguredSuffix": "to add LoRA files.",
    "lora.docs": "docs",
    "lora.filePlaceholder": "Select LoRA file",
    "lora.noFiles": "No LoRA files found",
    "lora.removeTitle": "Remove LoRA",
    "lora.removeDisabledTitle": "Cannot remove LoRAs while streaming",
    "lora.strategyLabel": "Strategy:",
    "lora.strategy.permanent": "Permanent Merge",
    "lora.strategy.runtime": "Runtime PEFT",
    "lora.scaleLabel": "Scale:",
    "denoise.title": "Denoising Step List",
    "denoise.reset": "Reset",
    "denoise.stepLabel": "Step {index}:",
    "denoise.validation": "Step {current} must be lower than Step {previous}",
    "transition.disabled": "First block cannot have transitions",
    "transition.header": "Temporal Transition Settings",
    "transition.blend": "Temporal Blend:",
    "transition.linear": "Linear",
    "transition.slerp": "Slerp",
    "transition.steps": "Transition Steps:",
    "media.title": "Media Picker",
    "media.loading": "Loading images...",
    "media.uploading": "Uploading...",
    "media.upload": "Upload",
    "media.empty": "No images found. Upload an image to get started.",
    "media.availableCount": "{count} images available, sorted by most recent",
    "media.availableNone": "No images available",
    "bug.title": "Report Bug",
    "bug.description": "Follow these steps to report a bug with diagnostic logs.",
    "bug.copyTitle": "Copy Logs",
    "bug.copyHint": "Click the button below to copy logs to your clipboard.",
    "bug.copied": "Copied!",
    "bug.loading": "Loading...",
    "bug.createTitle": "Create Bug Report",
    "bug.createHint": "Click the button below to create a bug report on GitHub and then attach the logs from your clipboard.",
    "bug.createButton": "Create Bug Report",
    "bug.error.fetchCopy": "Failed to fetch or copy logs",
    "imageManager.label": "Reference Images",
    "imageManager.tooltip": "Select reference images for VACE conditioning. Images will guide the video generation style and content.",
    "imageManager.addImage": "Add Image",
    "imageManager.referenceAlt": "Reference {index}",
    "imageManager.removeImage": "Remove image",
    "status.na": "N/A",
    "status.freeLora": "FREE Y2K LORA 4 U!!! CLICK & DOWNLOAD",
    "status.fps": "FPS",
    "status.bitrate": "Bitrate",
    "filePicker.selectFile": "Select file",
    "filePicker.noFiles": "No files found",
    "filePicker.root": "Root",
    "dialog.close": "Close",
    "sam3.status.downloading": "Downloading SAM3 models...",
    "sam3.status.downloadingProgress": "Downloading SAM3 models... {percentage}%",
    "sam3.status.uploadBefore": "Upload a video before generating masks.",
    "sam3.status.drawBoxFirst": "Draw a box around the person first.",
    "sam3.status.videoNotReady": "Video not ready yet. Try again in a moment.",
    "sam3.status.preparing": "Preparing SAM3...",
    "sam3.status.generating": "Generating SAM3 mask...",
    "sam3.status.ready": "Mask ready.",
    "sam3.error.generic": "Mask generation failed.",
    "sam3.error.title": "SAM3 Mask Error",
    "sam3.error.noDetections": "No masks detected. Try box prompt for better focus.",
    "burn.serverErrorTitle": "Server burn failed",
    "burn.serverErrorFallback": "Failed to render burn on server",
    "burn.missingSam3Mask": "Missing SAM3 mask for server burn.",
  },
  "ar-EG": {
    "language.australian": "أسترالي",
    "language.masri": "مصري",
    "header.logoAlt": "احرقني وأنا لسه سخن",
    "nav.upload": "رفع",
    "nav.play": "تشغيل",
    "nav.about": "عن",
    "about.title": "ليه عايز تتحرق؟",
    "about.body": `سينث فيديو مباشر.
ساميزدات فيديو مباشر.

شفّر الداتا، أو شفّر الإدراك.

الفيديو غالبًا عكس الخصوصية. ده من أكتر الوسائط المكشوفة،
أسهل حاجة تتكرر، وأسهل حاجة تنتشر، وأصعب حاجة تتحتوى.
أي حد يقدر يصورك، يعيد نشرّك، يأرشفك،
ويتفرج عليك من غير سياق، ومن غير موافقة، ومن غير ما تعرف.
السؤال مش بس إزاي تخلي حاجة بتاعتك، السؤال بقى:
إيه نوع الماكينة اللي تخليك موجود قدّام الناس من غير ما تبقى مقروء بالكامل؟

يمكن مش لازم تختفي.

بس لازم تبقى أصعب في القراءة.


مش خصوصية بالغياب، خصوصية بالتأويل.

ده مش عن استبدال التشفير. ده عن إن التشفير يعيش جوّه وسيط
بيدور لوحده في الثقافة. بدل ما ندفع كل حاجة لطبقات غير مرئية
من الرياضيات والكود، السطح نفسه يبدأ يشيل الشغل. اللي بتشوفه
يبقى جزء من تشكيل المعنى. طبقات، وتحوّلات، وميل بسيط،
وحسّ بالشك زي CYOA بيهرب من مرايات قاعات فيكتورية بعد نص الليل.

وده دلوقتي مش مجرد mp4.

ده بقى mp4p.

mp4-privy.

burn me while i'm hot ما بيسحبش المعنى من قدّام العين.
بيسيبه قدّام الكل، بس في شكل بيرفض يثبت في قراءة واحدة.
المحتوى بيتحرك بحرية. المعنى لأ. السينث ما بقاش ديكور.
بقى بيحرق نفسه جوّه الفيديو.

فالسؤال بيتحوّل.

مش إزاي ترجع مفاتيح الخصوصية الفاعلة.
لكن إزاي تحرق نفسك في السطح بطريقة تفضل بتاعتك.

ليه فيديو لايف؟

الفيديو اللايف عشوائي أكتر حسابيًا وبشكل مرهق. التوليف اللحظي
بيضيف اختلاف في توقيت الإطارات، الحالة الداخلية، وترتيب الرندر.
الاختلافات دي صغيرة، بس ثابتة كفاية إنها تفرق تشفيريًا،
ومش ثابتة كفاية إنها تسمح بإعادة التشغيل.

هنا، إطارات السينث اللايف بتتعتبر مدخلات لعملية التشفير.
كل فريم حرق بيبقى جزء من جدول المفاتيح للحمولات البصرية.
البايتات الدقيقة للفريم بتتعمل لها هاش وتتطوى في مادة مفتاح لكل فريم.
ده معناه إن سياق التشفير مربوط مش بس بإعدادات مجردة زي البرومبت أو السيد،
لكن بنتيجة رندر محددة حصلت في لحظة محددة.

الفيديو اللايف بيوفّر مصدر بصري مربوط بالوقت وغير قابل لإعادة التشغيل
تعتمد عليه بايبلاين التشفير، وده بيخلي الاسترجاع مرتبط بالظروف
اللي اتعمل فيها الحرق.

إزاي ده بيشتغل
1. ارفع فيديو تكون ظاهر فيه بوضوح
2. sam3 بيشتغل على اللقطات ويبني قناع فريم بفريم ليك
3. اختار ستايل y2k ومجموعة برومبت تحول بصري بألوان عالية ونقوش وأوفرلايز
4. دوس burn علشان تطلع نتيجة السينث وتربط البكسلات المقنّعة بمفاتيح بصرية لكل فريم
5. صدّر حاوية mp4p مع ملف مفتاح منفصل لفك التشفير بعدين
6. حمّل mp4p في المشغل علشان تشوف النسخة المحروقة من الفيديو
7. استورد ملف المفتاح علشان تعكس الشيفرة البصرية وترجع الأجزاء المقنّعة

إزاي التشفير وفك التشفير بيحصلوا
التشفير بيبدأ بمدخل سري، keyMaterial، ومجموعة ثابتة من بيانات بصرية عامة:
البرومبت، الإعدادات الثابتة، السيد، وإعدادات الماسك. منها النظام بيشتق
base_key عن طريق هاش لـ keyMaterial والبرومبت والإعدادات والسيد بـ sha256.

فيديو الحرق بيتعمل رندر، وإطاراته بتبقى مدخلات تشفير.
لكل فريم، البايتات الدقيقة بتتعمل لها هاش علشان تطلع frame_hash.
الهاش ده ورقم الفريم بيتجمعوا مع الـ base key باستخدام hmac-sha256
علشان يطلع frame_key فريد.

من كل frame_key، بيتولد keystream بتشغيل hmac-sha256
مع عدادات متزايدة وتقصير المخرجات لطول الفريم rgb الكامل
(الارتفاع × العرض × 3). الـ keystream ده بيتعمله xor مع بكسلات
rgb الأصلية جوّه الماسك. البكسلات برّه الماسك بتتصفّر.
النتيجة ضوضاء بصرية مشفّرة ومربوطة بفريم الحرق ده بالذات.

كل فريم مشفّر بيتخزن كـ png بقنوات rgba، حيث rgb فيها البكسلات المشفّرة
والألفا فيها الماسك. الإطارات دي بتتشفّر base64 وتتخزن في ملف mp4p
كـ encryptedMaskFrames، ومعاه maskFrameIndexMap بيربط كل حمولة بفريم حرقها.
وبالتوازي، الفيديو الأصلي والمولّف بيتشفّروا بـ aes-gcm بمفتاح متشتق
من keyMaterial عبر pbkdf2، ومعاه الملح والـ iv والـ auth tag في ميتاداتا mp4p.

فك التشفير بيحتاج ملف mp4p، ملف المفتاح، والفريمات المحروقة بالضبط.
النظام بيرجع يشتق نفس base_key، ويحسب كل frame_key من جديد،
ويعيد توليد الـ keystream، ويعمله xor مع الحمولات المخزنة
عشان يرجّع البكسلات المقنّعة. البكسلات دي بتتركّب تاني فوق فريمات الحرق
باستخدام الماسك ووضع الماسك المخزّن.

لو فريمات الحرق ومواد المفتاح مطابقة، المناطق المقنّعة بتظهر.
لو أي حاجة اختلفت، الـ keystream بيختلف والناتج بيبقى ضوضاء.

تفاصيل عن mp4p
الصيغة حاوية تشفير بتضم ستريمات وسائط مشفّرة، وحمولات شيفرة بصرية،
وميِتاداتا لازمة لإعادة توليدها. الفيديو الأصلي جوّه الحاوية بايتات مشفّرة بـ aes-gcm.
مينفعش يتسحب من غير key material، وموجود بس كحمولات بصرية لكل فريم
مربوطة رياضيًا بفيديو حرق محدد وملف مفتاح.

من غير سياق الحرق ده والمفتاح المطابق، مفيش حاجة مفهومة تتفك،
ولا فريمات جزئية تتسترجع، ولا ستريم أصلي يتسحب. mp4p بيخزن بايتات فيديو مشفّرة
مع الشروط اللي تحتها الفيديو ممكن يتعاد بناؤه، وبرّه الشروط دي
الصيغة بتتحول بس لنص مشفّر وضوضاء متزامنة.

تحسينات
سكيل + سرعة. سكيل + سررررعة.

1. التعامل مع فيديوهات أطول
2. قناع sam3 أحسن ووقت حقيقي مش مُعالج مسبقًا
3. lora الحالية 1.3b شغالة، بس بتخسر تفاصيل كتير مقارنة بنسخة 14b

وفي الآخر ده كله بيرجع للذاكرة والرام وكروت الشاشة وغيره

ليه y2k؟
لأن مع ما كل حاجة بتتسوء، y2k هو الستايل اللي لسه فاكر web1،
وقت ما الحاجات كانت ممكنة ومش متغرقة في بوت سلوب مستقطب
(مفيش حاجة ضد البوتات، كل حاجة ضد اللي فوقهم)



الخصوصية حق.`,
    "inputControls.title": "الإدخال والتحكم",
    "videoInput.title": "إدخال الفيديو",
    "videoInput.initializing": "جاري تهيئة الفيديو...",
    "videoInput.errorLabel": "خطأ في الفيديو:",
    "videoInput.dragBox": "اسحب لتحديد مربع حول الشخص",
    "videoInput.burning": "بيتحرق...",
    "videoInput.uploadToBegin": "ارفع فيديو علشان تبدأ",
    "videoInput.changeVideo": "غيّر الفيديو",
    "videoInput.play": "تشغيل",
    "videoInput.pause": "إيقاف مؤقت",
    "pipeline.title": "بايبلاين",
    "pipeline.selectPlaceholder": "اختار بايبلاين",
    "style.title": "ستايل",
    "sam3.title": "قناع SAM3",
    "sam3.requiresAccessPrefix": "لازم صلاحية من HF لـ",
    "sam3.requiresAccessSuffix": ". اطلب الوصول قبل ما تولّد الأقنعة.",
    "sam3.generating": "جاري التوليد...",
    "sam3.regenerateWithBox": "أعد التوليد مع المربع",
    "sam3.regenerateMask": "أعد توليد القناع",
    "sam3.useBoxPrompt": "استخدم مربع التحديد",
    "sam3.cancelBox": "إلغاء المربع",
    "sam3.noMaskDetected": "مفيش قناع اتكشف. جرّب مربع التحديد عشان التركيز يكون أحسن.",
    "sam3.drawBoxHint": "ارسم مربع على المعاينة وبعدين أعد التوليد.",
    "burn.title": "حرق",
    "burn.start": "ابدأ الحرق",
    "burn.cancel": "إلغاء الحرق",
    "burn.delete": "احذف الحرق",
    "burn.statusFromStart": "{status} من البداية.",
    "burn.status.recording": "تسجيل",
    "burn.status.preparing": "تجهيز",
    "export.exporting": "جاري التصدير...",
    "export.exportMp4p": "صدّر MP4P",
    "export.downloadKeyFile": "نزّل ملف المفتاح",
    "videoOutput.title": "إخراج الفيديو",
    "videoOutput.startPipeline": "ابدأ البايبلاين",
    "videoOutput.startPipelineHint": "اضغط لبدء البايبلاين.",
    "videoOutput.tapToPlay": "اضغط للتشغيل",
    "videoOutput.autoplayBlocked": "المتصفح وقف التشغيل التلقائي. اضغط عشان تكمل.",
    "videoOutput.downloadingModels": "جاري تنزيل الموديلات...",
    "videoOutput.warmingPipeline": "جاري تجهيز البايبلاين...",
    "videoOutput.generatingMask": "جاري توليد قناع SAM3...",
    "videoOutput.burning": "بيتحرق...",
    "videoOutput.loading": "تحميل...",
    "videoOutput.connecting": "جاري الاتصال...",
    "videoOutput.waitingForVideo": "مستني الفيديو...",
    "play.title": "شغّل MP4P",
    "play.loadMp4p": "حمّل MP4P",
    "play.loadKeyFile": "حمّل ملف المفتاح",
    "play.loadingMp4p": "جاري تحميل MP4P...",
    "play.noVideoLoaded": "مفيش فيديو محمّل.",
    "play.play": "تشغيل",
    "play.pause": "إيقاف مؤقت",
    "play.stop": "إيقاف",
    "play.restart": "إعادة التشغيل",
    "play.skipBack": "-5 ث",
    "play.skipForward": "+5 ث",
    "play.volume": "الصوت",
    "play.unmute": "شغّل الصوت",
    "play.mute": "كتم الصوت",
    "play.unlock": "فك القفل",
    "play.decrypting": "جاري فك التشفير...",
    "play.decryptWithKey": "فك التشفير بالمفتاح",
    "play.error.loadFailed": "فشل تحميل MP4P",
    "play.error.invalidKeyFile": "ملف المفتاح غير صالح",
    "play.error.decryptFailed": "فشل فك التشفير",
    "settings.title": "الإعدادات",
    "settings.pipelineId": "معرّف البايبلاين",
    "settings.selectPipeline": "اختار بايبلاين",
    "settings.lora.label": "LoRA Y2K",
    "settings.lora.tooltip": "فعّل LoRA الافتراضي لـ Y2K (المقياس 1.0). فعّله بس وإنت موقّف الفيديو.",
    "settings.toggle.on": "تشغيل",
    "settings.toggle.off": "إيقاف",
    "settings.lora.pauseToToggle": "وقّف الفيديو مؤقتًا علشان تغيّر الـ LoRA.",
    "settings.quantization.none": "بدون",
    "settings.quantization.fp8": "fp8_e4m3fn (ديناميكي)",
    "settings.spout.on": "تشغيل",
    "settings.spout.off": "إيقاف",
    "settings.spout.senderName": "اسم المرسل:",
    "settings.spout.senderTooltip": "اسم المرسل اللي هيبعت الفيديو لتطبيقات متوافقة مع Spout زي TouchDesigner وResolume وOBS.",
    "settings.spout.placeholder": "ScopeOut",
    "param.height.label": "الارتفاع:",
    "param.height.tooltip": "ارتفاع الفيديو الناتج بالبكسل. قيم أعلى تعطي تفاصيل أكتر عموديًا لكنها تقلل السرعة.",
    "param.width.label": "العرض:",
    "param.width.tooltip": "عرض الفيديو الناتج بالبكسل. قيم أعلى تعطي تفاصيل أكتر أفقيًا لكنها تقلل السرعة.",
    "param.seed.label": "البذرة:",
    "param.seed.tooltip": "بذرة عشوائية لتوليد قابل لإعادة الإنتاج. نفس البذرة مع نفس الإعدادات تعطي نتائج متشابهة.",
    "param.denoisingSteps.label": "قائمة خطوات إزالة الضوضاء",
    "param.denoisingSteps.tooltip": "قائمة خطوات إزالة الضوضاء في الانتشار. لازم تكون تنازلية. القيم الأقل تعني ضوضاء أقل للإزالة. خطوات أكتر تحسن الجودة لكنها تقلل السرعة.",
    "param.noiseController.label": "متحكم الضوضاء:",
    "param.noiseController.tooltip": "بيفعّل ضبط تلقائي لمقياس الضوضاء بناءً على الحركة المكتشفة. اقفلها للتحكم اليدوي في مقياس الضوضاء.",
    "param.noiseScale.label": "مقياس الضوضاء:",
    "param.noiseScale.tooltip": "بيتحكم في كمية الضوضاء المضافة أثناء التوليد. قيم أعلى تضيف تنوع وإبداع أكتر وقيم أقل تنتج نتائج أكثر ثباتًا.",
    "param.quantization.label": "التكميم:",
    "param.quantization.tooltip": "طريقة التكميم لموديل الانتشار. fp8_e4m3fn (ديناميكي) يقلل استخدام الذاكرة، لكنه ممكن يؤثر على الأداء والجودة. بدون يستخدم دقة كاملة ويستهلك ذاكرة أكتر لكنه لا يؤثر على الأداء والجودة.",
    "param.kvCacheAttentionBias.label": "انحياز الكاش:",
    "param.kvCacheAttentionBias.tooltip": "بيتحكم قد إيه نعتمد على الإطارات السابقة في الكاش أثناء التوليد. قيمة أقل تساعد تقلل تراكم الأخطاء وتمنع الحركة المتكررة. بيستخدم مقياس لوغاريتمي: 1.0 = اعتماد كامل على الإطارات السابقة، القيم الأصغر = اعتماد أقل. قيم شائعة: 0.3-0.7 لتأثير متوسط، 0.1-0.2 لتأثير قوي.",
    "param.loraMergeStrategy.label": "استراتيجية LoRA:",
    "param.loraMergeStrategy.tooltip": "استراتيجية دمج LoRA بتأثر على الأداء وإمكانية التحديث. دمج دائم: أعلى أداء، بدون تحديثات وقت التشغيل. Runtime PEFT: أداء أقل، تحديثات فورية وقت التشغيل.",
    "param.loraScale.label": "المقياس:",
    "param.loraScale.tooltip": "تحكم في قوة LoRA. بيتحدّث تلقائيًا لما تسيب السلايدر أو تستخدم أزرار +/- . قيم شائعة: 0.0 = بدون تأثير، 1.0 = قوة كاملة. المدى الكامل من -10.0 إلى 10.0 حسب مواصفات LoRA.",
    "param.loraScaleDisabledDuringStream.label": "المقياس:",
    "param.loraScaleDisabledDuringStream.tooltip": "التعديل وقت التشغيل متعطّل مع استراتيجية الدمج الدائم. مقاييس LoRA ثابتة وقت التحميل. قيم شائعة: 0.0 = بدون تأثير، 1.0 = قوة كاملة. المدى الكامل من -10.0 إلى 10.0 حسب مواصفات LoRA.",
    "param.spoutSender.label": "مرسل Spout:",
    "param.spoutSender.tooltip": "إعدادات المرسل اللي هيبعت الفيديو لتطبيقات متوافقة مع Spout زي TouchDesigner وResolume وOBS.",
    "lora.title": "محولات LoRA",
    "lora.refreshTitle": "حدّث قائمة LoRA",
    "lora.addTitle": "أضف LoRA",
    "lora.addDisabledTitle": "مينفعش تضيف LoRA أثناء البث",
    "lora.noneConfiguredPrefix": "مفيش محولات LoRA متضبطة. اتبع",
    "lora.noneConfiguredSuffix": "لإضافة ملفات LoRA.",
    "lora.docs": "الوثائق",
    "lora.filePlaceholder": "اختار ملف LoRA",
    "lora.noFiles": "مفيش ملفات LoRA",
    "lora.removeTitle": "احذف LoRA",
    "lora.removeDisabledTitle": "مينفعش تشيل LoRA أثناء البث",
    "lora.strategyLabel": "الاستراتيجية:",
    "lora.strategy.permanent": "دمج دائم",
    "lora.strategy.runtime": "Runtime PEFT",
    "lora.scaleLabel": "المقياس:",
    "denoise.title": "قائمة خطوات إزالة الضوضاء",
    "denoise.reset": "إعادة ضبط",
    "denoise.stepLabel": "الخطوة {index}:",
    "denoise.validation": "الخطوة {current} لازم تكون أقل من الخطوة {previous}",
    "transition.disabled": "أول بلوك مينفعش فيه انتقالات",
    "transition.header": "إعدادات الانتقال الزمني",
    "transition.blend": "دمج زمني:",
    "transition.linear": "خطي",
    "transition.slerp": "Slerp",
    "transition.steps": "خطوات الانتقال:",
    "media.title": "مُنتقي الوسائط",
    "media.loading": "جاري تحميل الصور...",
    "media.uploading": "جاري الرفع...",
    "media.upload": "ارفع",
    "media.empty": "مفيش صور. ارفع صورة علشان تبدأ.",
    "media.availableCount": "{count} صورة متاحة، مرتبة حسب الأحدث",
    "media.availableNone": "مفيش صور متاحة",
    "bug.title": "بلّغ عن مشكلة",
    "bug.description": "اتبع الخطوات دي علشان تبلغ عن مشكلة مع سجلات التشخيص.",
    "bug.copyTitle": "انسخ السجلات",
    "bug.copyHint": "اضغط الزر اللي تحت لنسخ السجلات في الحافظة.",
    "bug.copied": "اتنسخت!",
    "bug.loading": "جاري التحميل...",
    "bug.createTitle": "أنشئ بلاغ مشكلة",
    "bug.createHint": "اضغط الزر اللي تحت علشان تعمل بلاغ مشكلة على GitHub وبعدين أرفق السجلات اللي في الحافظة.",
    "bug.createButton": "أنشئ بلاغ مشكلة",
    "bug.error.fetchCopy": "فشل جلب أو نسخ السجلات",
    "imageManager.label": "صور مرجعية",
    "imageManager.tooltip": "اختار صور مرجعية لتهيئة VACE. الصور هتوجّه ستايل ومحتوى توليد الفيديو.",
    "imageManager.addImage": "أضف صورة",
    "imageManager.referenceAlt": "مرجع {index}",
    "imageManager.removeImage": "احذف الصورة",
    "status.na": "غير متاح",
    "status.freeLora": "LoRA Y2K مجانية ليك!!! دوس وحمّل",
    "status.fps": "إطارات/ث",
    "status.bitrate": "معدل البت",
    "filePicker.selectFile": "اختار ملف",
    "filePicker.noFiles": "مفيش ملفات",
    "filePicker.root": "الجذر",
    "dialog.close": "إغلاق",
    "sam3.status.downloading": "جاري تنزيل نماذج SAM3...",
    "sam3.status.downloadingProgress": "جاري تنزيل نماذج SAM3... {percentage}%",
    "sam3.status.uploadBefore": "ارفع فيديو قبل ما تولّد الأقنعة.",
    "sam3.status.drawBoxFirst": "ارسم مربع حوالين الشخص الأول.",
    "sam3.status.videoNotReady": "الفيديو لسه مش جاهز. جرّب تاني بعد شوية.",
    "sam3.status.preparing": "جاري تجهيز SAM3...",
    "sam3.status.generating": "جاري توليد قناع SAM3...",
    "sam3.status.ready": "القناع جاهز.",
    "sam3.error.generic": "فشل توليد القناع.",
    "sam3.error.title": "خطأ قناع SAM3",
    "sam3.error.noDetections": "مفيش أقنعة اتكشفت. جرّب مربع التحديد عشان التركيز يبقى أحسن.",
    "burn.serverErrorTitle": "فشل حرق السيرفر",
    "burn.serverErrorFallback": "فشل تنفيذ الحرق على السيرفر",
    "burn.missingSam3Mask": "قناع SAM3 مفقود لحرق السيرفر.",
  },
};

const DEFAULT_LANGUAGE: Language = "en-AU";
const STORAGE_KEY = "bmwih-language";

interface I18nContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const I18nContext = createContext<I18nContextValue>({
  language: DEFAULT_LANGUAGE,
  setLanguage: () => {},
  t: key => key,
});

const interpolate = (template: string, vars?: Record<string, string | number>) => {
  if (!vars) return template;
  return Object.entries(vars).reduce(
    (acc, [key, value]) => acc.replaceAll(`{${key}}`, String(value)),
    template
  );
};

export function I18nProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === "undefined") {
      return DEFAULT_LANGUAGE;
    }
    const stored = window.localStorage.getItem(STORAGE_KEY);
    return stored === "ar-EG" || stored === "en-AU" ? stored : DEFAULT_LANGUAGE;
  });

  useEffect(() => {
    if (typeof window === "undefined") return;
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language === "ar-EG" ? "ar" : "en-AU";
    document.documentElement.dir = language === "ar-EG" ? "rtl" : "ltr";
  }, [language]);

  const t = useCallback(
    (key: string, vars?: Record<string, string | number>) => {
      const template =
        translations[language][key] ??
        translations[DEFAULT_LANGUAGE][key] ??
        key;
      return interpolate(template, vars);
    },
    [language]
  );

  const value = useMemo(() => ({ language, setLanguage, t }), [language, t]);

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export const useI18n = () => useContext(I18nContext);
